name = "portfolio"
compatibility_date = "2024-01-01"
pages_build_output_dir = ".vercel/output/static"

[env.production]
compatibility_date = "2024-01-01"

# Compatibility flags for Node.js support
compatibility_flags = ["nodejs_compat"]

